// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPcjzbz-vUhXmLx2QbJ10maMbrwHXPTc',
    appId: '1:191802439908:web:31b6bc2ac2a3a2a67a54f1',
    messagingSenderId: '191802439908',
    projectId: 'dice-roller-ar',
    authDomain: 'dice-roller-ar.firebaseapp.com',
    storageBucket: 'dice-roller-ar.firebasestorage.app',
    measurementId: 'G-2M71G0XME8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-sJZZ31kaHYBiFRnhx37w3BDMFzoi12s',
    appId: '1:191802439908:android:3e4072ad1d2b71c37a54f1',
    messagingSenderId: '191802439908',
    projectId: 'dice-roller-ar',
    storageBucket: 'dice-roller-ar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTg4aOReQOU-KSUKVIJZS89YS9yEKu6dc',
    appId: '1:191802439908:ios:3c863148bc9dc0027a54f1',
    messagingSenderId: '191802439908',
    projectId: 'dice-roller-ar',
    storageBucket: 'dice-roller-ar.firebasestorage.app',
    iosBundleId: 'com.ssafadi.diceRollerAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTg4aOReQOU-KSUKVIJZS89YS9yEKu6dc',
    appId: '1:191802439908:ios:3c863148bc9dc0027a54f1',
    messagingSenderId: '191802439908',
    projectId: 'dice-roller-ar',
    storageBucket: 'dice-roller-ar.firebasestorage.app',
    iosBundleId: 'com.ssafadi.diceRollerAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByPcjzbz-vUhXmLx2QbJ10maMbrwHXPTc',
    appId: '1:191802439908:web:74d3ad729f2cc7227a54f1',
    messagingSenderId: '191802439908',
    projectId: 'dice-roller-ar',
    authDomain: 'dice-roller-ar.firebaseapp.com',
    storageBucket: 'dice-roller-ar.firebasestorage.app',
    measurementId: 'G-ESYKEBWJ9J',
  );

}